name = "Eclectic0136"
license = "MIT"
licenselink = "https://github.com/the-intern/Eclectic0136/blob/main/LICENSE"
description = "A theme for high performance customizable hugo websites."
homepage = "https://nobodybut.me"
tags = ["Website", "Performance", "Customizable"]
features = []
min_version = "0.02"

[author]
  name = "the intern"
  homepage = "https://example.me"
